--------------------------------------------------------
--  颇老捞 积己凳 - 格夸老-12岿-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESERVE
--------------------------------------------------------

  CREATE TABLE "DDIT"."RESERVE" 
   (	"RESERVE_NO" NUMBER, 
	"USER_ID" VARCHAR2(20 BYTE), 
	"RESERVE_TIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DDIT.RESERVE
SET DEFINE OFF;
Insert into DDIT.RESERVE (RESERVE_NO,USER_ID,RESERVE_TIME) values (1,'user',to_date('2020/12/24','RRRR/MM/DD'));
Insert into DDIT.RESERVE (RESERVE_NO,USER_ID,RESERVE_TIME) values (2,'user2',to_date('2020/12/24','RRRR/MM/DD'));
Insert into DDIT.RESERVE (RESERVE_NO,USER_ID,RESERVE_TIME) values (3,'user3',to_date('2020/12/24','RRRR/MM/DD'));
--------------------------------------------------------
--  DDL for Index RESERVE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DDIT"."RESERVE_PK" ON "DDIT"."RESERVE" ("RESERVE_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESERVE
--------------------------------------------------------

  ALTER TABLE "DDIT"."RESERVE" MODIFY ("RESERVE_NO" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."RESERVE" ADD CONSTRAINT "RESERVE_PK" PRIMARY KEY ("RESERVE_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
