--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "DDIT"."USERS" 
   (	"USER_ID" VARCHAR2(20 BYTE), 
	"NICKNAME" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DDIT"."USERS"."USER_ID" IS '아이디';
   COMMENT ON COLUMN "DDIT"."USERS"."NICKNAME" IS '닉네임';
   COMMENT ON COLUMN "DDIT"."USERS"."PASSWORD" IS '비밀번호';
REM INSERTING into DDIT.USERS
SET DEFINE OFF;
Insert into DDIT.USERS (USER_ID,NICKNAME,PASSWORD) values ('user','유저','1234');
Insert into DDIT.USERS (USER_ID,NICKNAME,PASSWORD) values ('admin','관리자','password');
Insert into DDIT.USERS (USER_ID,NICKNAME,PASSWORD) values ('guest','비회원','guest');
Insert into DDIT.USERS (USER_ID,NICKNAME,PASSWORD) values ('user2','유저2','1234');
Insert into DDIT.USERS (USER_ID,NICKNAME,PASSWORD) values ('user3','유저3','1234');
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DDIT"."TABLE1_PK" ON "DDIT"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "DDIT"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
