--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "DDIT"."BOARD" 
   (	"TITLE" VARCHAR2(30 BYTE), 
	"CONTENT" VARCHAR2(120 BYTE), 
	"USER_ID" VARCHAR2(30 BYTE), 
	"B_DATE" DATE DEFAULT SYSDATE, 
	"BOARD_NO" NUMBER, 
	"CATEGORY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "DDIT"."BOARD"."TITLE" IS '제목';
   COMMENT ON COLUMN "DDIT"."BOARD"."CONTENT" IS '게시판';
   COMMENT ON COLUMN "DDIT"."BOARD"."USER_ID" IS '유저ID';
   COMMENT ON COLUMN "DDIT"."BOARD"."B_DATE" IS '작성시간';
   COMMENT ON COLUMN "DDIT"."BOARD"."BOARD_NO" IS '글고유번호';
   COMMENT ON COLUMN "DDIT"."BOARD"."CATEGORY" IS '주제';
REM INSERTING into DDIT.BOARD
SET DEFINE OFF;
Insert into DDIT.BOARD (TITLE,CONTENT,USER_ID,B_DATE,BOARD_NO,CATEGORY) values ('식당문의','학원 근처 식당추가좀 해주세요','user',to_date('2020/12/24','RRRR/MM/DD'),1,'식당문의');
Insert into DDIT.BOARD (TITLE,CONTENT,USER_ID,B_DATE,BOARD_NO,CATEGORY) values ('건의드립니다.','버그가 너무많아요','user2',to_date('2020/12/24','RRRR/MM/DD'),2,'건의사항');
Insert into DDIT.BOARD (TITLE,CONTENT,USER_ID,B_DATE,BOARD_NO,CATEGORY) values ('필독!','다 추가하기 너무 힘들어요','admin',to_date('2020/12/24','RRRR/MM/DD'),3,'공지사항');
--------------------------------------------------------
--  DDL for Index BOARD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DDIT"."BOARD_PK" ON "DDIT"."BOARD" ("BOARD_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "DDIT"."BOARD" ADD CONSTRAINT "BOARD_PK" PRIMARY KEY ("BOARD_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DDIT"."BOARD" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."BOARD" MODIFY ("BOARD_NO" NOT NULL ENABLE);
