--------------------------------------------------------
--  파일이 생성됨 - 목요일-12월-24-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOXNAME
--------------------------------------------------------

  CREATE TABLE "DDIT"."BOXNAME" 
   (	"BOX_NAME" VARCHAR2(30 BYTE), 
	"BOX_TEL" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DDIT.BOXNAME
SET DEFINE OFF;
Insert into DDIT.BOXNAME (BOX_NAME,BOX_TEL) values ('대전도시락','042-254-9061');
--------------------------------------------------------
--  DDL for Index BOXNAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DDIT"."BOXNAME_PK" ON "DDIT"."BOXNAME" ("BOX_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table BOXNAME
--------------------------------------------------------

  ALTER TABLE "DDIT"."BOXNAME" ADD CONSTRAINT "BOXNAME_PK" PRIMARY KEY ("BOX_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DDIT"."BOXNAME" MODIFY ("BOX_NAME" NOT NULL ENABLE);
