--------------------------------------------------------
--  파일이 생성됨 - 토요일-12월-26-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESTAURANTS
--------------------------------------------------------

  CREATE TABLE "DDIT"."RESTAURANTS" 
   (	"RES_ID" NUMBER(30,0), 
	"RES_NAME" VARCHAR2(50 BYTE), 
	"COUSINE" VARCHAR2(20 BYTE), 
	"OPEN_TIME" VARCHAR2(10 BYTE), 
	"ADD1" VARCHAR2(60 BYTE), 
	"DISTANCE" NUMBER(4,0), 
	"CLOSE_TIME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into DDIT.RESTAURANTS
SET DEFINE OFF;
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (9,'소호차이나','중식',null,'대전 중구 중앙로79번길 31',205,null);
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (1,'스시생각','일식','11:30','대전광역시 중구 선화서로 7 2층',51,'22:00');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (2,'신가네매운떡볶이 대흥은행점','분식','10:30','대전 중구 선화서로 4',73,'21:00');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (6,'맥도날드 대전 센트럴DT점','패스트푸드','08:00','대전 중구 중앙로 64',21,'24:00');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (3,'괴산올갱이','한식',null,'대전 중구 보문로 253-27',83,null);
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (4,'맘스터치','패스트푸드','10:30','대전 중구 선화서로 7 1층',13,'22:30');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (5,'선화동소머리해장국','한식','09:00','대전 중구 선화로 128',825,'23:00');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (7,'오복식탁','한식','11:30','대전 중구 중앙로112번길 24',293,'20:30');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (8,'바로그집','분식','11:00','대전 중구 중앙로 145 지하상가 C나 61호',303,'22:00');
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (10,'요리왕','중식',null,'대전 중구 보문로260번길 8',278,null);
Insert into DDIT.RESTAURANTS (RES_ID,RES_NAME,COUSINE,OPEN_TIME,ADD1,DISTANCE,CLOSE_TIME) values (11,'이화수 전통 육개장','한식','8:00','대전 중구 중교로 38',495,'23:00');
--------------------------------------------------------
--  DDL for Index RESTAURANTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DDIT"."RESTAURANTS_PK" ON "DDIT"."RESTAURANTS" ("RES_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESTAURANTS
--------------------------------------------------------

  ALTER TABLE "DDIT"."RESTAURANTS" MODIFY ("RES_ID" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."RESTAURANTS" ADD CONSTRAINT "RESTAURANTS_PK" PRIMARY KEY ("RES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "DDIT"."RESTAURANTS" MODIFY ("RES_NAME" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."RESTAURANTS" MODIFY ("ADD1" NOT NULL ENABLE);
  ALTER TABLE "DDIT"."RESTAURANTS" MODIFY ("DISTANCE" NOT NULL ENABLE);
